name: bundler

on:
  pull_request:

  push:
    branches:
      - 3.6

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

defaults:
  run:
    shell: bash

jobs:
  bundler:
    name: Bundler ${{ matrix.bundler.name }} on ${{ matrix.os.name }} (${{ matrix.ruby.name }})
    runs-on: ${{ matrix.os.value }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - { name: Ubuntu, value: ubuntu-24.04 }

        ruby:
          - { name: ruby-3.1, value: 3.1.7 }
          - { name: ruby-3.2, value: 3.2.8 }
          - { name: ruby-3.3, value: 3.3.8 }
          - { name: ruby-3.4, value: 3.4.3 }

        bundler:
          - { name: 2, value: '' }
          - { name: 3, value: 3.0.0 }

        include:
          - { os: { name: macOS, value: macos-15 }, bundler: { name: 2, value: '' }, ruby: { name: ruby-3.1, value: 3.1.7 }, timeout: 90 }
          - { os: { name: macOS, value: macos-15 }, bundler: { name: 2, value: '' }, ruby: { name: ruby-3.2, value: 3.2.8 }, timeout: 90 }
          - { os: { name: macOS, value: macos-15 }, bundler: { name: 2, value: '' }, ruby: { name: ruby-3.3, value: 3.3.8 }, timeout: 90 }
          - { os: { name: macOS, value: macos-15 }, bundler: { name: 2, value: '' }, ruby: { name: ruby-3.4, value: 3.4.3 }, timeout: 90 }

          - { os: { name: Windows, value: windows-2025 }, bundler: { name: 2, value: '' }, ruby: { name: ruby-3.1, value: 3.1.7 }, timeout: 150 }
          - { os: { name: Windows, value: windows-2025 }, bundler: { name: 2, value: '' }, ruby: { name: ruby-3.2, value: 3.2.8 }, timeout: 150 }
          - { os: { name: Windows, value: windows-2025 }, bundler: { name: 2, value: '' }, ruby: { name: ruby-3.3, value: 3.3.8 }, timeout: 150 }
          - { os: { name: Windows, value: windows-2025 }, bundler: { name: 2, value: '' }, ruby: { name: ruby-3.4, value: 3.4.3 }, timeout: 150 }

          - { os: { name: Ubuntu, value: ubuntu-24.04 }, bundler: { name: 2, value: '' }, ruby: { name: jruby, value: jruby-9.4.12.0 } }
          - { os: { name: Windows, value: windows-2025 }, bundler: { name: 2, value: '' }, ruby: { name: jruby, value: jruby-9.4.12.0 } }

    env:
      RGV: ..
      RUBYOPT: --disable-gems
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      # TODO:
      # * Go back to ruby/setup-ruby once https://github.com/ruby/setup-ruby/pull/762 is released
      # * Figure out regression in gcc packages, my fork is pinned to https://github.com/ntkme/setup-msys2-gcc/releases/tag/v20250509.003447 because newer releases break our tests for some reason
      - name: Setup ruby
        uses: deivid-rodriguez/setup-ruby@dev
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
      - name: Setup java
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          distribution: temurin
          java-version: 19.0.2
        if: matrix.os.name == 'Windows' && matrix.ruby.name == 'jruby'
      - name: Install graphviz (Ubuntu)
        run: sudo apt-get install graphviz -y
        if: matrix.bundler.value == '' && matrix.os.name == 'Ubuntu'
      - name: Replace version
        run: BUNDLER_SPEC_SUB_VERSION=${{ matrix.bundler.value }} bin/rake override_version
        if: matrix.bundler.value != ''
      - name: Prepare dependencies
        run: |
          bin/rake dev:deps
      - name: Run Test (CRuby)
        run: |
          bin/parallel_rspec
        working-directory: ./bundler
        if: matrix.ruby.name != 'jruby'
      - name: Run Test (JRuby)
        run: |
          bin/parallel_rspec --tag jruby_only --tag jruby
        working-directory: ./bundler
        if: matrix.ruby.name == 'jruby' && matrix.os.name == 'Ubuntu'
      - name: Run a warbler project
        run: |
          bin/rake bundler:install:local
          cd bundler/spec/realworld/fixtures/warbler
          bundle install
          bundle exec warble
          java -jar warbler.jar
        if: matrix.ruby.name == 'jruby' && matrix.os.name == 'Ubuntu'

    timeout-minutes: ${{ matrix.timeout || 60 }}
