name: daily-bundler

on:
  schedule:
    - cron: '0 0 * * *'

  push:
    branches:
      - deivid-rodriguez/check-windows-ruby-fix

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  daily_bundler:
    name: Bundler (ruby-head on ${{ matrix.os.name }})
    runs-on: ${{ matrix.os.value }}
    strategy:
      matrix:
        os:
          - { name: Ubuntu, value: ubuntu-24.04 }
          - { name: Windows, value: windows-2022 }
    if: github.repository == 'rubygems/rubygems'
    env:
      RGV: ..
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Ruby
        uses: ruby/setup-ruby@32110d4e311bd8996b2a82bf2a43b714ccc91777 # v1.221.0
        with:
          ruby-version: ruby-head
          bundler: none

      - name: Show Ruby version
        run: ruby --version

      - name: Install graphviz (Ubuntu)
        run: sudo apt-get install graphviz -y
        if: matrix.os.name == 'Ubuntu'

      - name: Prepare dependencies
        run: |
          bin/rake spec:parallel_deps

      - name: Run Test
        run: |
          bin/rspec spec/install/global_cache_spec.rb:56
        working-directory: bundler

      - name: Get previous status
        if: always()
        run: echo "OLD_STATUS=$(curl -sS 'https://api.github.com/repos/rubygems/rubygems/actions/workflows/daily-bundler.yml/runs?event=schedule&branch=master' | jq '.workflow_runs | .[1].conclusion')" >> $GITHUB_ENV

      - uses: 8398a7/action-slack@28ba43ae48961b90635b50953d216767a6bea486 # v3.16.2
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: failure() && env.OLD_STATUS == '"success"'

    timeout-minutes: 60
